# Generated by Django 5.2.1 on 2025-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='answer',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='question',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_id',
            field=models.CharField(default='user_temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.CharField(default='user_temp', max_length=255),
            preserve_default=False,
        ),
    ]
